<?php 
$hello = 'delo';
// === BEGIN REACT ENQUEUE SCRIPTS ===
// Enqueue main.js generated by React build
wp_enqueue_script('your-react-app', get_template_directory_uri() . '/build/static/js/main.f4246b8e.js', array(), null, true);

// Enqueue main.css generated by React build
wp_enqueue_style('your-react-app-styles', get_template_directory_uri() . '/build/static/css/main.92813139.css');
// === END REACT ENQUEUE SCRIPTS ===
$tello = 'rrr';